### ISSUE TITLE
When link to the site with app is opened, then in app homepage is opened instead of particular link 

### ISSUE THREAD

**Issue by AlexTr** [unaio/una-mobile-app#16]
с андроид приложением: когда в браузере на телефоне открываешь линк сайта где есть мобильное приложение* - открывается главная страница, а не сам линк. Как вариант либо убрать такой вызов либо открывать страницу на которую илет линк в мобильном приложении. 

![9nip](https://user-images.githubusercontent.com/3324866/90631025-63abd000-e265-11ea-8616-47fe24d36e50.png)

**Comment by dralawady** [comment]
Any progress on this issue? it's really affecting all the android/ios notifications received for the app. when you open the notification from android, it does not take you to the corresponding notification tab in UNA, it takes you to the homepage.

**Comment by AlexTr** [comment]
@dralawady sorry, not yet, we'll try to address in the next version update
