### ISSUE TITLE
Android App startup

### ISSUE THREAD

**Issue by ciancostelloe** [unaio/una-mobile-app#34]
Once the android app is built and running on the emulator the startup screen does not go to the correct directory. 

Starting: info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.una.android/.MainActivity }

iOS app is working fine with the exact same link. Android app throws an error and does not display any page just ERROR.

**Comment by AlexTr** [comment]
Please post questions in forum - https://una.io/page/discussions-home
