### ISSUE TITLE
Documentations to build android app on Windows - is not clear

### ISSUE THREAD

**Issue by sanjaynidoni** [unaio/una-mobile-app#60]
una-mobile-app, build for android app,  step by step instructions are missing - Improve it if possible for beginners to follow

**Comment by AlexTr** [comment]
there are some videos, it's for mac but I hope it'll help  
https://una.io/p/una-mobile-apps-compile-ios-app-from  
https://una.io/p/una-mobile-apps-rebranding-under-mac-osx
